### PR TITLE
Handle invalid workflow YAML files gracefully

### LINKED ISSUE #411: The "Production" node changes from "default Invalid" to "Production master (WaitingForDeployment)" after restarting VS Code
**OS:** Mac
**Build Version:** 20210602.8

**Repro Steps:**

1. Create a static web app with **`"app"`** when entering a location of application code -> Expand the static web app
    -> There is an error in the "Production" node.
   image
2. Restart the VS Code -> Expand the static web app -> Check the "Production" node.
3. Check whether the "Production" node is unchanged.

**Expect:**
The "Production" node is unchanged.
image

**Actual:**
The "Production" node changes from "`default Invalid`" to "`Production master (WaitingForDeployment)`".
Screen Shot 2021-06-03 at 5 15 15 PM

**More Info:**

1. The "Production" node is unchanged on Windows after restarting VS Code.
2. This issue also reproduces when adding double quotes to `api` and `build`.

**Suggestion:**
It would be better to add a validation when entering a location of application code/Azure Function code/build output relative.

### PR DESCRIPTION
**Pull request by alexweininger**
Fixes #411 

Clicking on the invalid tree item opens and selects the invalid YAML block.

image

### CODE REVIEW

File: src/tree/EnvironmentTreeItem.ts [hunk 1]
```diff
@@ -187,6 +188,6 @@ export class EnvironmentTreeItem extends AzExtParentTreeItem implements IAzureRe
         const branch: string | undefined = remote ? await tryGetLocalBranch() : undefined;
         this.inWorkspace = this.parent.repositoryUrl === remote && this.branch === branch;
 
-        this.gitHubConfigGroupTreeItems = await GitHubConfigGroupTreeItem.createGitHubConfigGroupTreeItems(context, this);
+        [this.gitHubConfigGroupTreeItems, this.invalidGitHubConfigGroupTreeItems] = await GitHubConfigGroupTreeItem.createGitHubConfigGroupTreeItems(context, this);
```
Comment (alexweininger) [inline src/tree/EnvironmentTreeItem.ts:191]: I ended up using a tuple after trying to return InvalidTreeItems and the GithubConfigGroupTreeItems in an `AzExtTreeItem[]`. It would require more refactoring in this file and in `OpenYAMLConfigFile` and I think using a tuple was simpler.

Comment (nturinski) [reply src/tree/EnvironmentTreeItem.ts:191]: What if you had a boolean to indicate if the yaml is invalid?  

I think that could simplify the logic a little bit.  I think it would eliminate the need for the tuple.  You could just add some optional properties that you need for the range, I believe.

And use the boolean to determine which icon to use ofc :)

Comment (nturinski) [reply src/tree/EnvironmentTreeItem.ts:191]: Alternatively, I think if we edit this function a bit https://github.com/microsoft/vscode-azuretools/blob/344200a6fa49c426efd9debd61e86a75cbd2bce3/ui/src/tree/AzExtParentTreeItem.ts#L188 we could make it so you can specify the type of trees that are created on error rather than defaulting to a GenericTreeItem.

File: src/tree/GitHubConfigGroupTreeItem.ts [hunk 2]
```diff
@@ -49,12 +53,18 @@ export class GitHubConfigGroupTreeItem extends AzExtParentTreeItem {
 
             for (const yamlFile of yamlFiles) {
                 const yamlFilePath: string = join(workflowsDir, yamlFile);
-                const buildConfigs: BuildConfigs | undefined = await parseYamlFile(context, yamlFilePath);
-                buildConfigs && treeItems.push(new GitHubConfigGroupTreeItem(parent, yamlFilePath, buildConfigs));
+                try {
+                    const buildConfigs: BuildConfigs | undefined = await parseYamlFile(context, yamlFilePath);
+                    buildConfigs && treeItems.push(new GitHubConfigGroupTreeItem(parent, yamlFilePath, buildConfigs));
+                } catch (e) {
+                    if (e instanceof YAMLSyntaxError) {
```
Comment (nturinski) [inline src/tree/GitHubConfigGroupTreeItem.ts:60]: We should still have tree items for when the error is not `YAMLSyntaxError`.  In those cases, you can just make `parseError(e).message` the label.

File: src/tree/GitHubConfigGroupTreeItem.ts [hunk 3]
```diff
@@ -6,11 +6,14 @@
 import { pathExists, readdir } from "fs-extra";
 import { basename, join } from "path";
 import { ThemeIcon } from "vscode";
-import { AzExtParentTreeItem, AzExtTreeItem, IActionContext, TreeItemIconPath } from "vscode-azureextensionui";
+import { AzExtParentTreeItem, AzExtTreeItem, IActionContext, InvalidTreeItem, TreeItemIconPath } from "vscode-azureextensionui";
+// eslint-disable-next-line import/no-internal-modules
+import { YAMLSyntaxError } from "yaml/util";
```
Comment (nturinski) [inline src/tree/GitHubConfigGroupTreeItem.ts:11]: No other way to import? 😬

**Review by nturinski — COMMENTED** [review]
Could you add some tests to the existing `selectBuildConfigs.test` file where the workflow files has invalid entries?

File: src/tree/GitHubConfigGroupTreeItem.ts (hunk 3 above)
Comment (alexweininger) [reply src/tree/GitHubConfigGroupTreeItem.ts:11]: None that I'm aware of ☹️.  We added the `import/no-internal-modules` rule recently when we switched to the shared eslint config.

**Comment by nturinski** [comment]
Yeah, that sounds good.  I was thinking that if you had the invalid workflow that it could check that the invalid range is as expected.

File: src/tree/GitHubConfigGroupTreeItem.ts [hunk 4]
```diff
@@ -49,16 +76,20 @@ export class GitHubConfigGroupTreeItem extends AzExtParentTreeItem {
 
             for (const yamlFile of yamlFiles) {
                 const yamlFilePath: string = join(workflowsDir, yamlFile);
-                const buildConfigs: BuildConfigs | undefined = await parseYamlFile(context, yamlFilePath);
-                buildConfigs && treeItems.push(new GitHubConfigGroupTreeItem(parent, yamlFilePath, buildConfigs));
+                try {
```
Comment (nturinski) [inline src/tree/GitHubConfigGroupTreeItem.ts:79]: It's kind of a small distinction, but could you call `refreshImpl` here to initialize the tree item?  Right now we're doing two similar things in two places.

File: src/tree/GitHubConfigGroupTreeItem.ts [hunk 5]
```diff
@@ -69,7 +100,18 @@ export class GitHubConfigGroupTreeItem extends AzExtParentTreeItem {
         return false;
     }
 
+    public get errorRange(): Range | undefined {
+        return this.parseYamlError instanceof YAMLSyntaxError ? getRangeFromError(this.parseYamlError) : undefined;
+    }
+
     public async loadMoreChildrenImpl(): Promise<AzExtTreeItem[]> {
+        if (this.errorRange) {
```
Comment (nturinski) [inline src/tree/GitHubConfigGroupTreeItem.ts:108]: You should use `this.parseYamlError` as the check since that's what you're using everywhere else.

File: src/tree/GitHubConfigGroupTreeItem.ts [hunk 6]
```diff
@@ -21,19 +23,44 @@ export type BuildConfigs = {
...
     public yamlFilePath: string;
     public buildConfigs: BuildConfigs | undefined;
 
-    public constructor(parent: EnvironmentTreeItem, yamlFilePath: string, buildConfigs: BuildConfigs) {
+    public constructor(parent: EnvironmentTreeItem, yamlFilePath: string, buildConfigs: BuildConfigs, public parseYamlError?: unknown) {
         super(parent);
         this.yamlFilePath = yamlFilePath;
         this.buildConfigs = buildConfigs;
         this.id = `${parent.id}-${this.yamlFilePath}`;
+        this.commandArgs = [this];
```
Comment (nturinski) [inline src/tree/GitHubConfigGroupTreeItem.ts:55]: I don't think this is necessary to fill out
> /**
     * The arguments to pass in when executing `commandId`. If not specified, this tree item will be used.
     */

File: src/tree/GitHubConfigGroupTreeItem.ts [hunk 7]
```diff
@@ -21,19 +23,44 @@ export type BuildConfigs = {
...
+    }
+
+    public get label(): string {
+        return this.parseYamlError ? localize('invalidGitHubConfig', 'Invalid GitHub Configuration') : localize('gitHubConfig', 'GitHub Configuration');
+    }
+
+    public get commandId(): string | undefined {
+        return this.parseYamlError ? 'staticWebApps.openYAMLConfigFile' : undefined;
```
Comment (nturinski) [inline src/tree/GitHubConfigGroupTreeItem.ts:63]: Shouldn't this command id exist on the GenericTreeItem that you create (similar to the GitHubConfigTreeItems?)

Comment (alexweininger) [reply src/tree/GitHubConfigGroupTreeItem.ts:63]: I put it here because I think more users will click the GitHubConfigGroupTreeItem than the GenericTreeItem child. The issue I had with putting the command on the error message was users might not know that clicking the error takes them to the YAML. What do you think?

Comment (nturinski) [reply src/tree/GitHubConfigGroupTreeItem.ts:62]: Yeah, I guess it's fine, it's just a little weird to me that it's inconsistent.  I would say maybe we should put it on both then?

**Review by nturinski — APPROVED** [review]
